---
- name: Load sops-encrypted values
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print out the root password to the console
      debug: 
        var: lookup('community.sops.sops', 'site-secrets.sops.yaml')