apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: example-sopssecret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:Mwr0zA3IKnmqqG5xJ5wqRA==,iv:c+JLgWA74odyuPDhT8w8eimi8n1A50y/L0X7McxFv1k=,tag:g9cBu/ADMhZzDwhR7Nl5LA==,type:str]
          labels:
            label1: ENC[AES256_GCM,data:fVk/SGHE,iv:f2r1r7FspoDmkwfNBpiIa82kcsVROBUEOX0Nqb7sFjM=,tag:RPZmlRH4aLYESd5RUjpnug==,type:str]
          annotations:
            key1: ENC[AES256_GCM,data:ws6QLzPQ,iv:umSqHGd5vFzn9mQ6hvzUbFRXt6QrBfql3Y6NiEGXbvg=,tag:woKgWH2JAsl+2geeeyz+mA==,type:str]
          stringData:
            data-name0: ENC[AES256_GCM,data:R33GdhmYvALqYbQ=,iv:YLbNzzAz45S2CLa2HwL6Hp1MyTnZmQpAe7NK0Tvbrpo=,tag:Z4FJuBNcSvPZiU8U0FHb/Q==,type:str]
          data:
            data-name1: ENC[AES256_GCM,data:QL/oDi4KwGpZQN3bDNNIGg==,iv:1ky8ZoYT5N+EUYly//sxWzjgcL7U4ZTHzOG61ucXaOw=,tag:CWrRjY6v9EVoEhluvbvM6Q==,type:str]
        - name: ENC[AES256_GCM,data:mRsk3i76FCRzxlpPc3o=,iv:0n8//T5QDjXY5vvl2CPXTfQSY8hAa5CqUuGGmRMMBx4=,tag:AMGfPBs+RtPly4x9+wam1Q==,type:str]
          labels:
            jenkins.io/credentials-type: ENC[AES256_GCM,data:0kI7PLV04DFm/k2QymJt2w==,iv:iQneLG1dFs2qPAwQy74EYcajUBLZaUOCZQvYMl1gSlM=,tag:/+jAWHGtazHLe9kionUGLQ==,type:str]
          annotations:
            jenkins.io/credentials-description: ENC[AES256_GCM,data:dGVQleP6+Qg5m4y6hfKjRzrnmw9hzBsNCHNQ,iv:zArIlVKFZHX09L7nacVP7t/lAQFH8n42mE445AhAY8I=,tag:EkZlyaoFAikzt/b6CgwT0w==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:DcX2uRq3t6Se8Q==,iv:2jzEssG/FWqx+P6DqH5UZD7E+HPy0Q7p2YNIZN7aqGM=,tag:s7+ZuahUT3QuZEmXcOUeMg==,type:str]
            password: ENC[AES256_GCM,data:mq6fxYtbIxxW15c=,iv:3L7arkKThseFpeqZZrLjVKMjbRVtLdg2VfN4yym98+w=,tag:Vgr76utN7qPQCs2l4vOguA==,type:str]
        - name: ENC[AES256_GCM,data:SqCTFfIhsMFaDQ==,iv:Juf+08S7U2FJ9RyZBuPSX3KwxCudm7n7O6cuE4OrSE8=,tag:5YBJaDNsvu7tVLMcTHhSdg==,type:str]
          stringData:
            token: ENC[AES256_GCM,data:c/nequLpYE7Wd3RVPcZpBC6DlkZagCIrc9aEFGZoJ0/sBdxgrJZDu8xNknnAEMB4PbQAYns4j1OzWBVJcYhDZQ==,iv:wM4EkMeDYyW8/39hrQ3Mo/jhiX11f3RzzC+N/6iS7fM=,tag:0BJBUV1i+Rt65RPIwbRUeQ==,type:str]
        - name: ENC[AES256_GCM,data:FqTWtbOp4DbN+vUT,iv:dVXTEioQ6Seu9rA4sw6ttD1Lu2EtoAxweYacf78hmUM=,tag:S2wH98S9/f0mTdeLXgywow==,type:str]
          type: ENC[AES256_GCM,data:SOyiB4QbZvPhpm/wJA2Et5+ayOoIFhypX7MZk+gQ,iv:C+VyGN7n+nhlTxgDAy+6d/WC3dWkjfhn5H5glzRA6tg=,tag:1VSW/iXSjY90DX7ZXqztxQ==,type:str]
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:UNbpTPEZ02q5x5ickQjHyyY0SbCRz6YA3ahbtLWVtBUpFWswj4gCgg2k+bXAAs1f68yLgEjq50riMGlrzM5rUPZrHFNsvIGex31Ey1+vhEIvzbv7g0pDjBasNLkNDmMDS2fpWJeFAZIYedCTcD01hwE5da6YmU4CNxjv/XNrYA==,iv:4bqW8tedH7kACHAYawQUOdydqX/HRm+K0RkiwTg5v/M=,tag:6qA1BIzRtC4Wh+SQyWVwbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rzw9f9dvspwwykddan6ytllraywpume4jqx3enenu9m3ls493sjsr3slew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVzFHclYyQzVQVHhSaS9M
            SVFQK0tscDFZMEh3OEhxWDlod3h4ak5sVjBJClZ6TWFjUXRqaGIyaFRsZUxuc3Yz
            bjlXdVEvNXY4VncwcTZlTHVhNWcxU0EKLS0tIEhvSEczU1dFMmc4N3hFcGdLQkhH
            WlJVZWZCRnQzQ0FQVXFsZkJYOUdTcmcKobueilql7Tl0jcGjPswVuQguDH5JGnZd
            TNvuheFnHZfUa/0awwtoA/gct4Uxfa7wNJDNV0ujoExgnDA7axRQ8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T13:56:59Z"
    mac: ENC[AES256_GCM,data:N7B6ETt3oQKb187BJ2a5+CIQyqtel9dtKy4+9waEY2yRP7/2J18EWrILO9z2ZhSHz3Shq6NksluANvqARXBTDEgOHcKcDwvs2EZKUnvxpCrGRyjQ/6SKJWJmtAVp8a3yuqozsO0XCVDPmGGa3Nr+W9zwonXHBoq75LvYKqhInRk=,iv:fjwhg4lZaEyilhTKJMFkh/i5PYpBWQZge47hrcg8Boo=,tag:V5tQlXKTlAabXUQSJT7N4Q==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.7.3
